version: '3'
services:
  librarian-0:
    image: daedalus2718/libri:latest
    command: [
      "librarian", "start",
      "--nSubscriptions", "2",
      "--publicPort", "20100",
      "--localPort", "20100",
      "--localHost", "librarian-0",
      "--publicHost", "librarian-0",
      "--bootstraps", "librarian-0:20100"
    ]
    ports:
     - "20100:20100"
  librarian-1:
    image: daedalus2718/libri:latest
    command: [
      "librarian", "start",
      "--nSubscriptions", "2",
      "--publicPort", "20101",
      "--localPort", "20101",
      "--localHost", "librarian-1",
      "--publicHost", "librarian-1",
      "--bootstraps", "librarian-0:20100"
    ]
    ports:
     - "20101:20101"
  librarian-2:
    image: daedalus2718/libri:latest
    command: [
      "librarian", "start",
      "--nSubscriptions", "2",
      "--publicPort", "20102",
      "--localPort", "20102",
      "--localHost", "librarian-2",
      "--publicHost", "librarian-2",
      "--bootstraps", "librarian-0:20100"
    ]
    ports:
     - "20102:20102"
  tester:
    image: daedalus2718/libri:latest
    command: ["test", "-h"]
  author:
    image: daedalus2718/libri:latest
    command: ["author", "-h"]
