version: 2
jobs:
  build:
    working_directory: /go/src/github.com/drausin/libri
    docker:
      - image: daedalus2718/libri-build
    steps:
      - checkout
      - setup_remote_docker
      # TODO (restore deps cache?)
      - run:
          name: install deps
          command: |
            go get -d -u ./...
            make tools
      # TODO save deps cache?
      - run:
          name: build
          command: |
            make build          # ensure everything builds ok
            make build-static   # build linux binary for Docker image
            make docker-image   # ensure Docker image builds ok, even though only used on deployment
      - store_artifacts:
          path: deploy/bin
      - run:
          name: test
          command: |
            case ${CIRCLE_NODE_INDEX} in
              0)
                make test-cover
                make acceptance
                bash <(curl -s https://codecov.io/bash) -f test-coverage-merged.cov
                ;;
              1)
                make lint
                ;;
            esac
      - store_artifacts:
          path: acceptance.log

      - deploy:
          name: push docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              docker login -e ${DOCKER_EMAIL} -u $D{OCKER_USER} -p ${DOCKER_PASS}
              docker push daedalus2718/libri:latest
            fi
