// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	StoredPeer
	StoredPeers
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Peer is the basic information associated with each peer in the network.
type StoredPeer struct {
	// big-endian byte representation of 32-byte ID
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// self-reported name of the peer
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// public IP address
	AddressIp string `protobuf:"bytes,3,opt,name=address_ip,json=addressIp" json:"address_ip,omitempty"`
	// public address TCP port
	AddressPort int32 `protobuf:"varint,4,opt,name=address_port,json=addressPort" json:"address_port,omitempty"`
	// epoch time (seconds since 1970 UTC) of the latest response from the node.
	LatestResponse int64 `protobuf:"varint,5,opt,name=latest_response,json=latestResponse" json:"latest_response,omitempty"`
}

func (m *StoredPeer) Reset()                    { *m = StoredPeer{} }
func (m *StoredPeer) String() string            { return proto.CompactTextString(m) }
func (*StoredPeer) ProtoMessage()               {}
func (*StoredPeer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StoredPeer) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *StoredPeer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StoredPeer) GetAddressIp() string {
	if m != nil {
		return m.AddressIp
	}
	return ""
}

func (m *StoredPeer) GetAddressPort() int32 {
	if m != nil {
		return m.AddressPort
	}
	return 0
}

func (m *StoredPeer) GetLatestResponse() int64 {
	if m != nil {
		return m.LatestResponse
	}
	return 0
}

// Peers is a collection of Peer objects.
type StoredPeers struct {
	// list of peers
	Peers [][]byte `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (m *StoredPeers) Reset()                    { *m = StoredPeers{} }
func (m *StoredPeers) String() string            { return proto.CompactTextString(m) }
func (*StoredPeers) ProtoMessage()               {}
func (*StoredPeers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StoredPeers) GetPeers() [][]byte {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*StoredPeer)(nil), "server.StoredPeer")
	proto.RegisterType((*StoredPeers)(nil), "server.StoredPeers")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xcf, 0x3d, 0x6a, 0xc4, 0x30,
	0x10, 0x05, 0x60, 0xe4, 0x3f, 0xf0, 0xd8, 0x71, 0x60, 0x48, 0xa1, 0x26, 0xa0, 0x38, 0x45, 0x54,
	0xa5, 0xc9, 0x29, 0xd2, 0x19, 0xe5, 0x00, 0x46, 0x41, 0x43, 0x30, 0x64, 0x2d, 0x31, 0x23, 0xf6,
	0x32, 0x7b, 0xd9, 0x65, 0x6d, 0x2f, 0xdb, 0xbd, 0xf9, 0x5e, 0x33, 0x0f, 0x9e, 0x24, 0x47, 0xf6,
	0x7f, 0xf4, 0x99, 0x38, 0xe6, 0x88, 0x8d, 0x10, 0x9f, 0x89, 0xc7, 0x8b, 0x02, 0xf8, 0xc9, 0x91,
	0x29, 0x4c, 0x44, 0x8c, 0x03, 0x14, 0x4b, 0xd0, 0xca, 0x28, 0xdb, 0xbb, 0x62, 0x09, 0x88, 0x50,
	0xad, 0xfe, 0x44, 0xba, 0x30, 0xca, 0xb6, 0x6e, 0xcb, 0xf8, 0x0a, 0xe0, 0x43, 0x60, 0x12, 0x99,
	0x97, 0xa4, 0xcb, 0xad, 0x69, 0x0f, 0xf9, 0x4e, 0xf8, 0x06, 0xfd, 0xbd, 0x4e, 0x91, 0xb3, 0xae,
	0x8c, 0xb2, 0xb5, 0xeb, 0x0e, 0x9b, 0x22, 0x67, 0xfc, 0x80, 0xe7, 0x7f, 0x9f, 0x49, 0xf2, 0xcc,
	0x24, 0x29, 0xae, 0x42, 0xba, 0x36, 0xca, 0x96, 0x6e, 0xd8, 0xd9, 0x1d, 0x3a, 0xbe, 0x43, 0xf7,
	0x78, 0x4e, 0xf0, 0x05, 0xea, 0x74, 0x0b, 0x5a, 0x99, 0xd2, 0xf6, 0x6e, 0x3f, 0x7e, 0x9b, 0x6d,
	0xd1, 0xd7, 0x35, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x9d, 0xe8, 0x10, 0xe2, 0x00, 0x00, 0x00,
}
