# later
# - persistent volumes
# - readiness probe
# - separate bootstrap StatefulSet/IPs
# - load-balanced endpoint for authors
apiVersion: v1
kind: Service
metadata:
  name: libri
spec:
  ports:
    - port: 20100
      targetPort: 20100
      name: grpc
  clusterIP: None
  selector:
    app: libri
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: librarian
spec:
  serviceName: libri
  replicas: 3
  template:
    metadata:
      labels:
        app: libri
    spec:
      containers:
        - name: libriarian
          image: daedalus2718/libri:latest  # develop branch
          args: ["librarian", "start"]
          env:
            - name: LIBRI_BOOTSTRAPS
              value: "librarians-0.libri.default.svc.cluster.local:20100"
            - name: LIBRI_PUBLICIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 20100
              name: grpc
