// Code generated by protoc-gen-go.
// source: libri/librarian/api/documents.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	libri/librarian/api/documents.proto
	libri/librarian/api/librarian.proto

It has these top-level messages:
	Document
	Envelope
	Entry
	Metadata
	PageKeys
	Page
	RequestMetadata
	ResponseMetadata
	PingRequest
	PingResponse
	IntroduceRequest
	IntroduceResponse
	FindRequest
	FindResponse
	PeerAddress
	StoreRequest
	StoreResponse
	GetRequest
	GetResponse
	PutRequest
	PutResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Document contains either an Envelope, Entry, or Page message.
type Document struct {
	// Types that are valid to be assigned to Contents:
	//	*Document_Envelope
	//	*Document_Entry
	//	*Document_Page
	Contents isDocument_Contents `protobuf_oneof:"contents"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isDocument_Contents interface {
	isDocument_Contents()
}

type Document_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,oneof"`
}
type Document_Entry struct {
	Entry *Entry `protobuf:"bytes,2,opt,name=entry,oneof"`
}
type Document_Page struct {
	Page *Page `protobuf:"bytes,3,opt,name=page,oneof"`
}

func (*Document_Envelope) isDocument_Contents() {}
func (*Document_Entry) isDocument_Contents()    {}
func (*Document_Page) isDocument_Contents()     {}

func (m *Document) GetContents() isDocument_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Document) GetEnvelope() *Envelope {
	if x, ok := m.GetContents().(*Document_Envelope); ok {
		return x.Envelope
	}
	return nil
}

func (m *Document) GetEntry() *Entry {
	if x, ok := m.GetContents().(*Document_Entry); ok {
		return x.Entry
	}
	return nil
}

func (m *Document) GetPage() *Page {
	if x, ok := m.GetContents().(*Document_Page); ok {
		return x.Page
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Document) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Document_OneofMarshaler, _Document_OneofUnmarshaler, _Document_OneofSizer, []interface{}{
		(*Document_Envelope)(nil),
		(*Document_Entry)(nil),
		(*Document_Page)(nil),
	}
}

func _Document_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Document)
	// contents
	switch x := m.Contents.(type) {
	case *Document_Envelope:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Envelope); err != nil {
			return err
		}
	case *Document_Entry:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Entry); err != nil {
			return err
		}
	case *Document_Page:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Page); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Document.Contents has unexpected type %T", x)
	}
	return nil
}

func _Document_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Document)
	switch tag {
	case 1: // contents.envelope
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Envelope)
		err := b.DecodeMessage(msg)
		m.Contents = &Document_Envelope{msg}
		return true, err
	case 2: // contents.entry
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Entry)
		err := b.DecodeMessage(msg)
		m.Contents = &Document_Entry{msg}
		return true, err
	case 3: // contents.page
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Page)
		err := b.DecodeMessage(msg)
		m.Contents = &Document_Page{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Document_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Document)
	// contents
	switch x := m.Contents.(type) {
	case *Document_Envelope:
		s := proto.Size(x.Envelope)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Document_Entry:
		s := proto.Size(x.Entry)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Document_Page:
		s := proto.Size(x.Page)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Envelope contains the (encrypted) keys used to encrypt a particular Entry and its Pages. It uses
// DCDH exchange from the author to a particular reader. The envelope contains the encrypted
// secret, which gives the 4 keys required to decrypt the Entry and Pages.
type Envelope struct {
	// ECDSA public key of the entry author/sender
	AuthorPublicKey []byte `protobuf:"bytes,1,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	// ECDSA public key of the entry reader/recipient
	ReaderPublicKey []byte `protobuf:"bytes,2,opt,name=reader_public_key,json=readerPublicKey,proto3" json:"reader_public_key,omitempty"`
	// 32-byte key of the Entry whose encryption keys are being sent
	EntryKey []byte `protobuf:"bytes,3,opt,name=entry_key,json=entryKey,proto3" json:"entry_key,omitempty"`
	// ciphertext of the encryption keys (the Diffie-Hellman secret) for the given Entry; the
	// secret plaintext contains (in order)
	// 1) 32-byte AES-256 key, used to enrypt Pages and Entry metadata
	// 2) 32-byte Page initialization vector (IV) seed
	// 3) 32-byte Page ciphertext HMAC-256 key
	// 4) 12-byte metadata block cipher initialization vector
	EncryptionKeysCiphertext []byte `protobuf:"bytes,4,opt,name=encryption_keys_ciphertext,json=encryptionKeysCiphertext,proto3" json:"encryption_keys_ciphertext,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Envelope) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *Envelope) GetReaderPublicKey() []byte {
	if m != nil {
		return m.ReaderPublicKey
	}
	return nil
}

func (m *Envelope) GetEntryKey() []byte {
	if m != nil {
		return m.EntryKey
	}
	return nil
}

func (m *Envelope) GetEncryptionKeysCiphertext() []byte {
	if m != nil {
		return m.EncryptionKeysCiphertext
	}
	return nil
}

// Entry is the main unit of storage in the Libri network.
type Entry struct {
	// ECDSA public key of the entry author
	AuthorPublicKey []byte `protobuf:"bytes,1,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	// created epoch time (seconds since 1970-01-01)
	CreatedTime int64 `protobuf:"varint,2,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// 32-byte MAC of metatadata ciphertext, encrypted with the 32-byte Entry AES-256 key and
	// 12-byte metadata block cipher IV
	MetadataCiphertextMac []byte `protobuf:"bytes,3,opt,name=metadata_ciphertext_mac,json=metadataCiphertextMac,proto3" json:"metadata_ciphertext_mac,omitempty"`
	// ciphertext of marshalled Metadata message properties
	MetadataCiphertext []byte `protobuf:"bytes,4,opt,name=metadata_ciphertext,json=metadataCiphertext,proto3" json:"metadata_ciphertext,omitempty"`
	// 32-byte MAC of the contents ciphertext, across all blocks (in order)
	ContentsCiphertextMac []byte `protobuf:"bytes,5,opt,name=contents_ciphertext_mac,json=contentsCiphertextMac,proto3" json:"contents_ciphertext_mac,omitempty"`
	// total length (in bytes) of the ciphertext, across all pages
	ContentsCiphertextSize uint64 `protobuf:"varint,6,opt,name=contents_ciphertext_size,json=contentsCiphertextSize" json:"contents_ciphertext_size,omitempty"`
	// contents of the entry, either a single Page or a list of page keys
	//
	// Types that are valid to be assigned to Contents:
	//	*Entry_Page
	//	*Entry_PageKeys
	Contents isEntry_Contents `protobuf_oneof:"contents"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isEntry_Contents interface {
	isEntry_Contents()
}

type Entry_Page struct {
	Page *Page `protobuf:"bytes,7,opt,name=page,oneof"`
}
type Entry_PageKeys struct {
	PageKeys *PageKeys `protobuf:"bytes,8,opt,name=page_keys,json=pageKeys,oneof"`
}

func (*Entry_Page) isEntry_Contents()     {}
func (*Entry_PageKeys) isEntry_Contents() {}

func (m *Entry) GetContents() isEntry_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Entry) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *Entry) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Entry) GetMetadataCiphertextMac() []byte {
	if m != nil {
		return m.MetadataCiphertextMac
	}
	return nil
}

func (m *Entry) GetMetadataCiphertext() []byte {
	if m != nil {
		return m.MetadataCiphertext
	}
	return nil
}

func (m *Entry) GetContentsCiphertextMac() []byte {
	if m != nil {
		return m.ContentsCiphertextMac
	}
	return nil
}

func (m *Entry) GetContentsCiphertextSize() uint64 {
	if m != nil {
		return m.ContentsCiphertextSize
	}
	return 0
}

func (m *Entry) GetPage() *Page {
	if x, ok := m.GetContents().(*Entry_Page); ok {
		return x.Page
	}
	return nil
}

func (m *Entry) GetPageKeys() *PageKeys {
	if x, ok := m.GetContents().(*Entry_PageKeys); ok {
		return x.PageKeys
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Entry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Entry_OneofMarshaler, _Entry_OneofUnmarshaler, _Entry_OneofSizer, []interface{}{
		(*Entry_Page)(nil),
		(*Entry_PageKeys)(nil),
	}
}

func _Entry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Entry)
	// contents
	switch x := m.Contents.(type) {
	case *Entry_Page:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Page); err != nil {
			return err
		}
	case *Entry_PageKeys:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PageKeys); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Entry.Contents has unexpected type %T", x)
	}
	return nil
}

func _Entry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Entry)
	switch tag {
	case 7: // contents.page
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Page)
		err := b.DecodeMessage(msg)
		m.Contents = &Entry_Page{msg}
		return true, err
	case 8: // contents.page_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PageKeys)
		err := b.DecodeMessage(msg)
		m.Contents = &Entry_PageKeys{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Entry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Entry)
	// contents
	switch x := m.Contents.(type) {
	case *Entry_Page:
		s := proto.Size(x.Page)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entry_PageKeys:
		s := proto.Size(x.PageKeys)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Metadata is a map of (property, value) combinations.
type Metadata struct {
	Properties map[string][]byte `protobuf:"bytes,1,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Metadata) GetProperties() map[string][]byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

// PageKeys is an ordered list of keys to Page documents that comprise an Entry document.
type PageKeys struct {
	Keys [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (m *PageKeys) Reset()                    { *m = PageKeys{} }
func (m *PageKeys) String() string            { return proto.CompactTextString(m) }
func (*PageKeys) ProtoMessage()               {}
func (*PageKeys) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PageKeys) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Page is a portion (possibly all) of an Entry document.
type Page struct {
	// ECDSA public key of the entry author
	AuthorPublicKey []byte `protobuf:"bytes,1,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	// index of Page within Entry contents
	Index uint32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	// 32-byte MAC of ciphertext using the 32-byte Page ciphertext HMAC-256 key
	CiphertextMac []byte `protobuf:"bytes,3,opt,name=ciphertext_mac,json=ciphertextMac,proto3" json:"ciphertext_mac,omitempty"`
	// ciphertext of Page contents, encrypted using the 32-byte AES-256 key with the block cipher
	// initialized by the first 12 bytes of HMAC-256(IV seed, page index)
	Ciphertext []byte `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Page) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *Page) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Page) GetCiphertextMac() []byte {
	if m != nil {
		return m.CiphertextMac
	}
	return nil
}

func (m *Page) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func init() {
	proto.RegisterType((*Document)(nil), "api.Document")
	proto.RegisterType((*Envelope)(nil), "api.Envelope")
	proto.RegisterType((*Entry)(nil), "api.Entry")
	proto.RegisterType((*Metadata)(nil), "api.Metadata")
	proto.RegisterType((*PageKeys)(nil), "api.PageKeys")
	proto.RegisterType((*Page)(nil), "api.Page")
}

func init() { proto.RegisterFile("libri/librarian/api/documents.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x94, 0x6f, 0x6b, 0xd3, 0x50,
	0x14, 0xc6, 0x97, 0xa6, 0x99, 0xe9, 0x69, 0xeb, 0xf4, 0x3a, 0x35, 0x4c, 0x9c, 0x35, 0x22, 0x14,
	0x95, 0x16, 0x26, 0xc8, 0x10, 0xf7, 0xc6, 0x3f, 0x30, 0x18, 0x83, 0x12, 0x7d, 0x1f, 0x6e, 0x93,
	0xc3, 0x76, 0xb1, 0x49, 0x2e, 0x37, 0xb7, 0x63, 0xd9, 0x27, 0xf0, 0x85, 0xe0, 0x27, 0xf2, 0xbb,
	0xc9, 0x3d, 0xb9, 0xe9, 0x9f, 0xb5, 0xbe, 0xd8, 0x9b, 0xf6, 0xe6, 0x3e, 0xbf, 0x93, 0xf3, 0x1c,
	0xce, 0x43, 0xe0, 0xd5, 0x4c, 0x4c, 0x95, 0x18, 0x9b, 0x5f, 0xae, 0x04, 0xcf, 0xc7, 0x5c, 0x8a,
	0x71, 0x5a, 0x24, 0xf3, 0x0c, 0x73, 0x5d, 0x8e, 0xa4, 0x2a, 0x74, 0xc1, 0x5c, 0x2e, 0x45, 0xf8,
	0xcb, 0x01, 0xff, 0xab, 0x15, 0xd8, 0x5b, 0xf0, 0x31, 0xbf, 0xc2, 0x59, 0x21, 0x31, 0x70, 0x06,
	0xce, 0xb0, 0x7b, 0xd4, 0x1f, 0x71, 0x29, 0x46, 0xdf, 0xec, 0xe5, 0xe9, 0x4e, 0xb4, 0x00, 0x58,
	0x08, 0x1e, 0xe6, 0x5a, 0x55, 0x41, 0x8b, 0x48, 0xb0, 0xa4, 0x56, 0xd5, 0xe9, 0x4e, 0x54, 0x4b,
	0xec, 0x05, 0xb4, 0x25, 0xbf, 0xc0, 0xc0, 0x25, 0xa4, 0x43, 0xc8, 0x84, 0x5f, 0x98, 0x17, 0x91,
	0xf0, 0x19, 0xc0, 0x4f, 0x8a, 0x5c, 0x1b, 0x57, 0xe1, 0x5f, 0x07, 0xfc, 0xa6, 0x13, 0x7b, 0x03,
	0x0f, 0xf9, 0x5c, 0x5f, 0x16, 0x2a, 0x96, 0xf3, 0xe9, 0x4c, 0x24, 0xf1, 0x4f, 0xac, 0xc8, 0x53,
	0x2f, 0xda, 0xab, 0x85, 0x09, 0xdd, 0x9f, 0x61, 0x65, 0x58, 0x85, 0x3c, 0xc5, 0x35, 0xb6, 0x55,
	0xb3, 0xb5, 0xb0, 0x64, 0x9f, 0x41, 0x87, 0xac, 0x11, 0xe3, 0x12, 0xe3, 0xd3, 0x85, 0x11, 0x3f,
	0xc1, 0x01, 0xe6, 0x89, 0xaa, 0xa4, 0x16, 0x45, 0x6e, 0x88, 0x32, 0x4e, 0x84, 0xbc, 0x44, 0xa5,
	0xf1, 0x5a, 0x07, 0x6d, 0xa2, 0x83, 0x25, 0x71, 0x86, 0x55, 0xf9, 0x65, 0xa1, 0x87, 0xbf, 0x5d,
	0xf0, 0x68, 0xfe, 0x3b, 0x99, 0x7f, 0x09, 0xbd, 0x44, 0x21, 0xd7, 0x98, 0xc6, 0x5a, 0x64, 0x48,
	0xbe, 0xdd, 0xa8, 0x6b, 0xef, 0x7e, 0x88, 0x0c, 0xd9, 0x07, 0x78, 0x9a, 0xa1, 0xe6, 0x29, 0xd7,
	0x7c, 0xc5, 0x4f, 0x9c, 0xf1, 0xc4, 0x4e, 0xf0, 0xb8, 0x91, 0x97, 0x6e, 0xce, 0x79, 0xc2, 0xc6,
	0xf0, 0x68, 0x4b, 0x9d, 0x9d, 0x83, 0x6d, 0xd6, 0x98, 0x46, 0xcd, 0x36, 0x6e, 0x37, 0xf2, 0xea,
	0x46, 0x8d, 0xbc, 0xde, 0xe8, 0x18, 0x82, 0x6d, 0x75, 0xa5, 0xb8, 0xc1, 0x60, 0x77, 0xe0, 0x0c,
	0xdb, 0xd1, 0x93, 0xcd, 0xc2, 0xef, 0xe2, 0x06, 0x17, 0x01, 0xb9, 0xf7, 0x9f, 0x80, 0xb0, 0x77,
	0xd0, 0x31, 0xff, 0xb4, 0x8c, 0xc0, 0x5f, 0xc9, 0xa4, 0xa1, 0xcc, 0x02, 0x4c, 0x26, 0xa5, 0x3d,
	0xaf, 0xc5, 0xc9, 0x24, 0xfb, 0xdc, 0xce, 0xc8, 0x4e, 0x00, 0xa4, 0x2a, 0x24, 0x2a, 0x2d, 0xb0,
	0x0c, 0x9c, 0x81, 0x3b, 0xec, 0x1e, 0x3d, 0xa7, 0xf7, 0x34, 0xc8, 0x68, 0xb2, 0xd0, 0x69, 0x89,
	0xd1, 0x4a, 0xc1, 0xc1, 0x09, 0xec, 0xdd, 0x92, 0xd9, 0x03, 0x70, 0x9b, 0xad, 0x76, 0x22, 0x73,
	0x64, 0xfb, 0xe0, 0x5d, 0xf1, 0xd9, 0x1c, 0x6d, 0xf4, 0xea, 0x87, 0x8f, 0xad, 0x63, 0x27, 0x3c,
	0x04, 0xbf, 0xb1, 0xcb, 0x18, 0xb4, 0x69, 0x16, 0xe3, 0xa1, 0x17, 0xd1, 0x39, 0xfc, 0xe3, 0x40,
	0xdb, 0x00, 0x77, 0x0a, 0xce, 0x3e, 0x78, 0x22, 0x4f, 0xf1, 0x9a, 0xda, 0xf5, 0xa3, 0xfa, 0x81,
	0xbd, 0x86, 0xfb, 0x5b, 0x23, 0xd2, 0x4f, 0xd6, 0x36, 0x76, 0x08, 0xb0, 0x91, 0x88, 0x95, 0x9b,
	0xe9, 0x2e, 0x7d, 0x22, 0xde, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xec, 0x7c, 0x27, 0x49,
	0x04, 0x00, 0x00,
}
