// Code generated by protoc-gen-go.
// source: librarian/api/documents.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	librarian/api/documents.proto
	librarian/api/librarian.proto

It has these top-level messages:
	Document
	Envelope
	Entry
	EntryMetadata
	EntrySchema
	PageKeys
	Page
	RequestMetadata
	ResponseMetadata
	IntroduceRequest
	IntroduceResponse
	FindRequest
	FindResponse
	VerifyRequest
	VerifyResponse
	PeerAddress
	StoreRequest
	StoreResponse
	GetRequest
	GetResponse
	PutRequest
	PutResponse
	SubscribeRequest
	SubscribeResponse
	Publication
	Subscription
	BloomFilter
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CompressionCodec denotes whether and how the plaintext is compressed before encryption.
type CompressionCodec int32

const (
	CompressionCodec_NONE CompressionCodec = 0
	CompressionCodec_GZIP CompressionCodec = 1
)

var CompressionCodec_name = map[int32]string{
	0: "NONE",
	1: "GZIP",
}
var CompressionCodec_value = map[string]int32{
	"NONE": 0,
	"GZIP": 1,
}

func (x CompressionCodec) String() string {
	return proto.EnumName(CompressionCodec_name, int32(x))
}
func (CompressionCodec) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Document contains either an Envelope, Entry, or Page message.
type Document struct {
	// Types that are valid to be assigned to Contents:
	//	*Document_Envelope
	//	*Document_Entry
	//	*Document_Page
	Contents isDocument_Contents `protobuf_oneof:"contents"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isDocument_Contents interface {
	isDocument_Contents()
}

type Document_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,oneof"`
}
type Document_Entry struct {
	Entry *Entry `protobuf:"bytes,2,opt,name=entry,oneof"`
}
type Document_Page struct {
	Page *Page `protobuf:"bytes,3,opt,name=page,oneof"`
}

func (*Document_Envelope) isDocument_Contents() {}
func (*Document_Entry) isDocument_Contents()    {}
func (*Document_Page) isDocument_Contents()     {}

func (m *Document) GetContents() isDocument_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Document) GetEnvelope() *Envelope {
	if x, ok := m.GetContents().(*Document_Envelope); ok {
		return x.Envelope
	}
	return nil
}

func (m *Document) GetEntry() *Entry {
	if x, ok := m.GetContents().(*Document_Entry); ok {
		return x.Entry
	}
	return nil
}

func (m *Document) GetPage() *Page {
	if x, ok := m.GetContents().(*Document_Page); ok {
		return x.Page
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Document) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Document_OneofMarshaler, _Document_OneofUnmarshaler, _Document_OneofSizer, []interface{}{
		(*Document_Envelope)(nil),
		(*Document_Entry)(nil),
		(*Document_Page)(nil),
	}
}

func _Document_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Document)
	// contents
	switch x := m.Contents.(type) {
	case *Document_Envelope:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Envelope); err != nil {
			return err
		}
	case *Document_Entry:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Entry); err != nil {
			return err
		}
	case *Document_Page:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Page); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Document.Contents has unexpected type %T", x)
	}
	return nil
}

func _Document_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Document)
	switch tag {
	case 1: // contents.envelope
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Envelope)
		err := b.DecodeMessage(msg)
		m.Contents = &Document_Envelope{msg}
		return true, err
	case 2: // contents.entry
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Entry)
		err := b.DecodeMessage(msg)
		m.Contents = &Document_Entry{msg}
		return true, err
	case 3: // contents.page
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Page)
		err := b.DecodeMessage(msg)
		m.Contents = &Document_Page{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Document_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Document)
	// contents
	switch x := m.Contents.(type) {
	case *Document_Envelope:
		s := proto.Size(x.Envelope)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Document_Entry:
		s := proto.Size(x.Entry)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Document_Page:
		s := proto.Size(x.Page)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Envelope defines the public keys an author uses to share an entry encryption key with a
// particular reader. The shared ECDH secret is used with a key derivation function to generate the
// key encryption key (KEK), which contains 2 sub-keys:
// 1) 32-byte AES-256 key, used for encrypting/decrypting the entry encryption key (EEK)
// 2) 12-byte EEK block cipher initialization vector
// 3) 32-byte HMAC-256 key, used for EEK MAC
//
// This AES-256 EEK is then used to decrypt the EEK ciphertext, which contains 4 sub-keys:
// 1) 32-byte AES-256 key, used to enrypt Pages and Entry metadata
// 2) 32-byte Page initialization vector (IV) seed
// 3) 32-byte HMAC-256 key
// 4) 12-byte metadata block cipher initialization vector
type Envelope struct {
	// 32-byte key of the Entry whose encryption keys are being sent
	EntryKey []byte `protobuf:"bytes,1,opt,name=entry_key,json=entryKey,proto3" json:"entry_key,omitempty"`
	// ECDH public key of the entry author/sender
	AuthorPublicKey []byte `protobuf:"bytes,2,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	// ECDH public key of the entry reader/recipient
	ReaderPublicKey []byte `protobuf:"bytes,3,opt,name=reader_public_key,json=readerPublicKey,proto3" json:"reader_public_key,omitempty"`
	// ciphertext of 108-byte entry encryption key (EEK), encrypted with a KEK from the shared
	// ECDH shared secret
	EekCiphertext []byte `protobuf:"bytes,4,opt,name=eek_ciphertext,json=eekCiphertext,proto3" json:"eek_ciphertext,omitempty"`
	// 32-byte MAC of the EEK
	EekCiphertextMac []byte `protobuf:"bytes,5,opt,name=eek_ciphertext_mac,json=eekCiphertextMac,proto3" json:"eek_ciphertext_mac,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Envelope) GetEntryKey() []byte {
	if m != nil {
		return m.EntryKey
	}
	return nil
}

func (m *Envelope) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *Envelope) GetReaderPublicKey() []byte {
	if m != nil {
		return m.ReaderPublicKey
	}
	return nil
}

func (m *Envelope) GetEekCiphertext() []byte {
	if m != nil {
		return m.EekCiphertext
	}
	return nil
}

func (m *Envelope) GetEekCiphertextMac() []byte {
	if m != nil {
		return m.EekCiphertextMac
	}
	return nil
}

// Entry is the main unit of storage in the Libri network.
type Entry struct {
	// ECDSA public key of the entry author
	AuthorPublicKey []byte `protobuf:"bytes,1,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	// contents of the entry, either a single Page or a list of page keys
	//
	// Types that are valid to be assigned to Contents:
	//	*Entry_Page
	//	*Entry_PageKeys
	Contents isEntry_Contents `protobuf_oneof:"contents"`
	// created epoch time (seconds since 1970-01-01)
	CreatedTime int64 `protobuf:"varint,4,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// ciphertext of marshalled EntryMetadata message properties
	MetadataCiphertext []byte `protobuf:"bytes,5,opt,name=metadata_ciphertext,json=metadataCiphertext,proto3" json:"metadata_ciphertext,omitempty"`
	// 32-byte MAC of metatadata ciphertext, encrypted with the 32-byte Entry AES-256 key and
	// 12-byte metadata block cipher IV
	MetadataCiphertextMac []byte `protobuf:"bytes,6,opt,name=metadata_ciphertext_mac,json=metadataCiphertextMac,proto3" json:"metadata_ciphertext_mac,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isEntry_Contents interface {
	isEntry_Contents()
}

type Entry_Page struct {
	Page *Page `protobuf:"bytes,2,opt,name=page,oneof"`
}
type Entry_PageKeys struct {
	PageKeys *PageKeys `protobuf:"bytes,3,opt,name=page_keys,json=pageKeys,oneof"`
}

func (*Entry_Page) isEntry_Contents()     {}
func (*Entry_PageKeys) isEntry_Contents() {}

func (m *Entry) GetContents() isEntry_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Entry) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *Entry) GetPage() *Page {
	if x, ok := m.GetContents().(*Entry_Page); ok {
		return x.Page
	}
	return nil
}

func (m *Entry) GetPageKeys() *PageKeys {
	if x, ok := m.GetContents().(*Entry_PageKeys); ok {
		return x.PageKeys
	}
	return nil
}

func (m *Entry) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Entry) GetMetadataCiphertext() []byte {
	if m != nil {
		return m.MetadataCiphertext
	}
	return nil
}

func (m *Entry) GetMetadataCiphertextMac() []byte {
	if m != nil {
		return m.MetadataCiphertextMac
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Entry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Entry_OneofMarshaler, _Entry_OneofUnmarshaler, _Entry_OneofSizer, []interface{}{
		(*Entry_Page)(nil),
		(*Entry_PageKeys)(nil),
	}
}

func _Entry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Entry)
	// contents
	switch x := m.Contents.(type) {
	case *Entry_Page:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Page); err != nil {
			return err
		}
	case *Entry_PageKeys:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PageKeys); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Entry.Contents has unexpected type %T", x)
	}
	return nil
}

func _Entry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Entry)
	switch tag {
	case 2: // contents.page
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Page)
		err := b.DecodeMessage(msg)
		m.Contents = &Entry_Page{msg}
		return true, err
	case 3: // contents.page_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PageKeys)
		err := b.DecodeMessage(msg)
		m.Contents = &Entry_PageKeys{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Entry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Entry)
	// contents
	switch x := m.Contents.(type) {
	case *Entry_Page:
		s := proto.Size(x.Page)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entry_PageKeys:
		s := proto.Size(x.PageKeys)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// EntryMetadata contains metadata for an entry.
type EntryMetadata struct {
	// media/MIME type of the data
	MediaType string `protobuf:"bytes,1,opt,name=media_type,json=mediaType" json:"media_type,omitempty"`
	// codec used to compress the data
	CompressionCodec CompressionCodec `protobuf:"varint,2,opt,name=compression_codec,json=compressionCodec,enum=api.CompressionCodec" json:"compression_codec,omitempty"`
	// total ciphertext size across all pages
	CiphertextSize uint64 `protobuf:"varint,3,opt,name=ciphertext_size,json=ciphertextSize" json:"ciphertext_size,omitempty"`
	// MAC of the entire ciphertext
	CiphertextMac []byte `protobuf:"bytes,4,opt,name=ciphertext_mac,json=ciphertextMac,proto3" json:"ciphertext_mac,omitempty"`
	// total size of the entire uncompressed entry
	UncompressedSize uint64 `protobuf:"varint,5,opt,name=uncompressed_size,json=uncompressedSize" json:"uncompressed_size,omitempty"`
	// MAC of the entire uncompressed entry
	UncompressedMac []byte `protobuf:"bytes,6,opt,name=uncompressed_mac,json=uncompressedMac,proto3" json:"uncompressed_mac,omitempty"`
	// domain-specific metadata
	Properties map[string][]byte `protobuf:"bytes,7,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// (relative) filepath of the data contained in the entry
	Filepath string `protobuf:"bytes,8,opt,name=filepath" json:"filepath,omitempty"`
	// schema of the entry plaintext
	Schema *EntrySchema `protobuf:"bytes,9,opt,name=schema" json:"schema,omitempty"`
}

func (m *EntryMetadata) Reset()                    { *m = EntryMetadata{} }
func (m *EntryMetadata) String() string            { return proto.CompactTextString(m) }
func (*EntryMetadata) ProtoMessage()               {}
func (*EntryMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EntryMetadata) GetMediaType() string {
	if m != nil {
		return m.MediaType
	}
	return ""
}

func (m *EntryMetadata) GetCompressionCodec() CompressionCodec {
	if m != nil {
		return m.CompressionCodec
	}
	return CompressionCodec_NONE
}

func (m *EntryMetadata) GetCiphertextSize() uint64 {
	if m != nil {
		return m.CiphertextSize
	}
	return 0
}

func (m *EntryMetadata) GetCiphertextMac() []byte {
	if m != nil {
		return m.CiphertextMac
	}
	return nil
}

func (m *EntryMetadata) GetUncompressedSize() uint64 {
	if m != nil {
		return m.UncompressedSize
	}
	return 0
}

func (m *EntryMetadata) GetUncompressedMac() []byte {
	if m != nil {
		return m.UncompressedMac
	}
	return nil
}

func (m *EntryMetadata) GetProperties() map[string][]byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *EntryMetadata) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *EntryMetadata) GetSchema() *EntrySchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

// EntrySchema denotes the schema associated with the serialized plaintext of a particular entry.
// Schemas can be of any type (e.g., proto, avro, json, XML, etc).
//
// Clients can choose to do what they want with this schema, but commonly they will have a set of
// schemas they know how to handle explicitly.
type EntrySchema struct {
	// group owning the schema (commonly a Github user, e.g., 'drausin')
	Group string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	// project in which schema resides (commonly a Github project, e.g., 'libri')
	Project string `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	// path to schema file within project (e.g., 'libri/librarian/api/documents.proto')
	Path string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	// (optional) name of schema within file (e.g., 'EntrySchema')
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	// version of schema (commonly a semver tag, e.g., '0.1.0')
	Version string `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
}

func (m *EntrySchema) Reset()                    { *m = EntrySchema{} }
func (m *EntrySchema) String() string            { return proto.CompactTextString(m) }
func (*EntrySchema) ProtoMessage()               {}
func (*EntrySchema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EntrySchema) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *EntrySchema) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *EntrySchema) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *EntrySchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EntrySchema) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// PageKeys is an ordered list of keys to Page documents that comprise an Entry document.
type PageKeys struct {
	Keys [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (m *PageKeys) Reset()                    { *m = PageKeys{} }
func (m *PageKeys) String() string            { return proto.CompactTextString(m) }
func (*PageKeys) ProtoMessage()               {}
func (*PageKeys) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PageKeys) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Page is a portion (possibly all) of an Entry document.
type Page struct {
	// ECDSA public key of the entry author
	AuthorPublicKey []byte `protobuf:"bytes,1,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	// index of Page within Entry contents
	Index uint32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	// ciphertext of Page contents, encrypted using the 32-byte AES-256 key with the block cipher
	// initialized by the first 12 bytes of HMAC-256(IV seed, page index)
	Ciphertext []byte `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// 32-byte MAC of ciphertext using the 32-byte Page ciphertext HMAC-256 key
	CiphertextMac []byte `protobuf:"bytes,4,opt,name=ciphertext_mac,json=ciphertextMac,proto3" json:"ciphertext_mac,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Page) GetAuthorPublicKey() []byte {
	if m != nil {
		return m.AuthorPublicKey
	}
	return nil
}

func (m *Page) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Page) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *Page) GetCiphertextMac() []byte {
	if m != nil {
		return m.CiphertextMac
	}
	return nil
}

func init() {
	proto.RegisterType((*Document)(nil), "api.Document")
	proto.RegisterType((*Envelope)(nil), "api.Envelope")
	proto.RegisterType((*Entry)(nil), "api.Entry")
	proto.RegisterType((*EntryMetadata)(nil), "api.EntryMetadata")
	proto.RegisterType((*EntrySchema)(nil), "api.EntrySchema")
	proto.RegisterType((*PageKeys)(nil), "api.PageKeys")
	proto.RegisterType((*Page)(nil), "api.Page")
	proto.RegisterEnum("api.CompressionCodec", CompressionCodec_name, CompressionCodec_value)
}

func init() { proto.RegisterFile("librarian/api/documents.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x41, 0x4f, 0xeb, 0x46,
	0x10, 0xc6, 0x71, 0x02, 0xf6, 0x84, 0x10, 0xb3, 0x05, 0xd5, 0xa2, 0x82, 0x52, 0x4b, 0x6d, 0x53,
	0x40, 0x41, 0xa2, 0x52, 0x55, 0x55, 0xea, 0x05, 0x8a, 0x4a, 0x85, 0xa0, 0x91, 0xe1, 0xd4, 0x4b,
	0xb4, 0xd8, 0x53, 0xb2, 0x25, 0xb6, 0x57, 0xeb, 0x0d, 0xc2, 0x5c, 0x7a, 0xed, 0xad, 0xf7, 0xfe,
	0xae, 0xfe, 0x83, 0xfe, 0x91, 0x6a, 0xc7, 0x76, 0xe2, 0xe4, 0xf1, 0xa4, 0xf7, 0x4e, 0x9e, 0xf9,
	0xe6, 0x9b, 0xd9, 0xd9, 0x6f, 0x67, 0x0c, 0xfb, 0x53, 0xf1, 0xa0, 0xb8, 0x12, 0x3c, 0x3d, 0xe5,
	0x52, 0x9c, 0xc6, 0x59, 0x34, 0x4b, 0x30, 0xd5, 0xf9, 0x50, 0xaa, 0x4c, 0x67, 0xcc, 0xe6, 0x52,
	0x04, 0x7f, 0x59, 0xe0, 0xfc, 0x54, 0x05, 0xd8, 0x31, 0x38, 0x98, 0x3e, 0xe3, 0x34, 0x93, 0xe8,
	0x5b, 0x87, 0xd6, 0xa0, 0x7b, 0xd6, 0x1b, 0x72, 0x29, 0x86, 0x97, 0x15, 0x78, 0xb5, 0x16, 0xce,
	0x09, 0x2c, 0x80, 0x0e, 0xa6, 0x5a, 0x15, 0x7e, 0x8b, 0x98, 0x50, 0x31, 0xb5, 0x2a, 0xae, 0xd6,
	0xc2, 0x32, 0xc4, 0x3e, 0x87, 0xb6, 0xe4, 0x8f, 0xe8, 0xdb, 0x44, 0x71, 0x89, 0x32, 0xe2, 0x8f,
	0xa6, 0x10, 0x05, 0xce, 0x01, 0x9c, 0x28, 0x4b, 0xb5, 0xe9, 0x2a, 0xf8, 0xd7, 0x02, 0xa7, 0x3e,
	0x89, 0x7d, 0x06, 0x2e, 0x95, 0x18, 0x3f, 0x61, 0x41, 0xbd, 0x6c, 0x9a, 0xa3, 0xb5, 0x2a, 0xae,
	0xb1, 0x60, 0x47, 0xb0, 0xcd, 0x67, 0x7a, 0x92, 0xa9, 0xb1, 0x9c, 0x3d, 0x4c, 0x45, 0x44, 0xa4,
	0x16, 0x91, 0xfa, 0x65, 0x60, 0x44, 0x78, 0xc5, 0x55, 0xc8, 0x63, 0x5c, 0xe2, 0xda, 0x25, 0xb7,
	0x0c, 0x2c, 0xb8, 0x5f, 0xc2, 0x16, 0xe2, 0xd3, 0x38, 0x12, 0x72, 0x82, 0x4a, 0xe3, 0x8b, 0xf6,
	0xdb, 0x44, 0xec, 0x21, 0x3e, 0x5d, 0xcc, 0x41, 0x76, 0x02, 0x6c, 0x99, 0x36, 0x4e, 0x78, 0xe4,
	0x77, 0x88, 0xea, 0x2d, 0x51, 0x6f, 0x78, 0x14, 0xfc, 0xd3, 0x82, 0x0e, 0xc9, 0xf2, 0x76, 0xdb,
	0xd6, 0xdb, 0x6d, 0xd7, 0xca, 0xb5, 0xde, 0xa3, 0x1c, 0x3b, 0x01, 0xd7, 0x7c, 0x4d, 0x8d, 0xbc,
	0xd2, 0xb7, 0x37, 0x67, 0x5d, 0x63, 0x91, 0x9b, 0xc7, 0x92, 0x95, 0xcd, 0xbe, 0x80, 0xcd, 0x48,
	0x21, 0xd7, 0x18, 0x8f, 0xb5, 0x48, 0x90, 0xee, 0x65, 0x87, 0xdd, 0x0a, 0xbb, 0x17, 0x09, 0xb2,
	0x53, 0xf8, 0x24, 0x41, 0xcd, 0x63, 0xae, 0x79, 0x53, 0x81, 0xf2, 0x5a, 0xac, 0x0e, 0x35, 0x64,
	0xf8, 0x0e, 0x3e, 0x7d, 0x23, 0x81, 0xb4, 0x58, 0xa7, 0xa4, 0xdd, 0x77, 0x93, 0x6e, 0x78, 0xb4,
	0xf4, 0xe6, 0xff, 0xd9, 0xd0, 0x23, 0x71, 0x6e, 0x2a, 0x2a, 0xdb, 0x07, 0x48, 0x30, 0x16, 0x7c,
	0xac, 0x8b, 0x6a, 0x0a, 0xdd, 0xd0, 0x25, 0xe4, 0xbe, 0x90, 0xc8, 0xce, 0x61, 0x3b, 0xca, 0x12,
	0xa9, 0x30, 0xcf, 0x45, 0x96, 0x8e, 0xa3, 0x2c, 0xc6, 0x88, 0x44, 0xda, 0x3a, 0xdb, 0xa5, 0xeb,
	0x5f, 0x2c, 0xa2, 0x17, 0x26, 0x18, 0x7a, 0xd1, 0x0a, 0xc2, 0xbe, 0x86, 0x7e, 0xa3, 0xdf, 0x5c,
	0xbc, 0x96, 0x03, 0xda, 0x0e, 0xb7, 0x16, 0xf0, 0x9d, 0x78, 0x45, 0x33, 0x0f, 0x2b, 0x17, 0xab,
	0xe6, 0x21, 0x6a, 0x5e, 0x88, 0x1d, 0xc3, 0xf6, 0x2c, 0xad, 0x4f, 0xc1, 0xb8, 0xac, 0xd8, 0xa1,
	0x8a, 0x5e, 0x33, 0x40, 0x35, 0xbf, 0x81, 0x25, 0xac, 0x21, 0x57, 0xbf, 0x89, 0x9b, 0xba, 0xe7,
	0x00, 0x52, 0x65, 0x12, 0x95, 0x16, 0x98, 0xfb, 0x1b, 0x87, 0xf6, 0xa0, 0x7b, 0x16, 0x2c, 0xd6,
	0xac, 0x96, 0x6c, 0x38, 0x9a, 0x93, 0x08, 0x0f, 0x1b, 0x59, 0x6c, 0x0f, 0x9c, 0xdf, 0xc5, 0x14,
	0x25, 0xd7, 0x13, 0xdf, 0x21, 0x31, 0xe7, 0x3e, 0x1b, 0xc0, 0x7a, 0x1e, 0x4d, 0x30, 0xe1, 0xbe,
	0x4b, 0xf3, 0xe3, 0x2d, 0x6a, 0xdf, 0x11, 0x1e, 0x56, 0xf1, 0xbd, 0x1f, 0xa1, 0xbf, 0x72, 0x08,
	0xf3, 0xc0, 0xae, 0xc7, 0xd7, 0x0d, 0x8d, 0xc9, 0x76, 0xa0, 0xf3, 0xcc, 0xa7, 0x33, 0xac, 0x36,
	0xb1, 0x74, 0x7e, 0x68, 0x7d, 0x6f, 0x05, 0x7f, 0x42, 0xb7, 0x51, 0xd5, 0x10, 0x1f, 0x55, 0x36,
	0x93, 0x55, 0x72, 0xe9, 0x30, 0x1f, 0x36, 0xa4, 0xca, 0xfe, 0xc0, 0x48, 0x53, 0x01, 0x37, 0xac,
	0x5d, 0xc6, 0xcc, 0x2e, 0xe8, 0x09, 0x3d, 0x92, 0x1b, 0x92, 0x6d, 0xb0, 0x94, 0x57, 0x83, 0xec,
	0x86, 0x64, 0x9b, 0x0a, 0xcf, 0xa8, 0xcc, 0x3b, 0x93, 0xfa, 0x6e, 0x58, 0xbb, 0xc1, 0x01, 0x38,
	0xf5, 0x5a, 0x98, 0x4c, 0xda, 0x19, 0xeb, 0xd0, 0x1e, 0x6c, 0x86, 0x64, 0x07, 0x7f, 0x5b, 0xd0,
	0x36, 0x84, 0x8f, 0x5a, 0xd1, 0x1d, 0xe8, 0x88, 0x34, 0xc6, 0x17, 0x6a, 0xb7, 0x17, 0x96, 0x0e,
	0x3b, 0x00, 0x68, 0x6c, 0x4f, 0xf9, 0xa3, 0x69, 0x20, 0x1f, 0x38, 0x53, 0x47, 0x5f, 0x81, 0xb7,
	0x3a, 0xc9, 0xcc, 0x81, 0xf6, 0xed, 0xaf, 0xb7, 0x97, 0xde, 0x9a, 0xb1, 0x7e, 0xfe, 0xed, 0x97,
	0x91, 0x67, 0x3d, 0xac, 0xd3, 0xbf, 0xfc, 0xdb, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x19,
	0xa6, 0x95, 0xec, 0x05, 0x00, 0x00,
}
