// Code generated by protoc-gen-go.
// source: libri/common/storage/storage.proto
// DO NOT EDIT!

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	libri/common/storage/storage.proto

It has these top-level messages:
	Address
	QueryOutcomes
	QueryTypeOutcomes
	Peer
	RoutingTable
	DocumentMetrics
	ReplicationMetrics
*/
package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Address is a IPv4 address.
type Address struct {
	// IP address
	Ip string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// TCP port
	Port uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type QueryOutcomes struct {
	Requests  *QueryTypeOutcomes `protobuf:"bytes,1,opt,name=requests" json:"requests,omitempty"`
	Responses *QueryTypeOutcomes `protobuf:"bytes,2,opt,name=responses" json:"responses,omitempty"`
}

func (m *QueryOutcomes) Reset()                    { *m = QueryOutcomes{} }
func (m *QueryOutcomes) String() string            { return proto.CompactTextString(m) }
func (*QueryOutcomes) ProtoMessage()               {}
func (*QueryOutcomes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryOutcomes) GetRequests() *QueryTypeOutcomes {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *QueryOutcomes) GetResponses() *QueryTypeOutcomes {
	if m != nil {
		return m.Responses
	}
	return nil
}

// Responses contains statistics about a Peer's query history.
type QueryTypeOutcomes struct {
	// epoch time (seconds since 1970 UTC) of the earliest response from the peer
	Earliest int64 `protobuf:"varint,1,opt,name=earliest" json:"earliest,omitempty"`
	// epoch time of the latest response from the peer
	Latest int64 `protobuf:"varint,2,opt,name=latest" json:"latest,omitempty"`
	// number of queries sent to the peer
	NQueries uint64 `protobuf:"varint,3,opt,name=n_queries,json=nQueries" json:"n_queries,omitempty"`
	// number of queries that errored
	NErrors uint64 `protobuf:"varint,4,opt,name=n_errors,json=nErrors" json:"n_errors,omitempty"`
}

func (m *QueryTypeOutcomes) Reset()                    { *m = QueryTypeOutcomes{} }
func (m *QueryTypeOutcomes) String() string            { return proto.CompactTextString(m) }
func (*QueryTypeOutcomes) ProtoMessage()               {}
func (*QueryTypeOutcomes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryTypeOutcomes) GetEarliest() int64 {
	if m != nil {
		return m.Earliest
	}
	return 0
}

func (m *QueryTypeOutcomes) GetLatest() int64 {
	if m != nil {
		return m.Latest
	}
	return 0
}

func (m *QueryTypeOutcomes) GetNQueries() uint64 {
	if m != nil {
		return m.NQueries
	}
	return 0
}

func (m *QueryTypeOutcomes) GetNErrors() uint64 {
	if m != nil {
		return m.NErrors
	}
	return 0
}

// Peer is the basic information associated with each peer in the network.
type Peer struct {
	// big-endian byte representation of 32-byte ID
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// self-reported name of the peer
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// public IP address
	PublicAddress *Address `protobuf:"bytes,3,opt,name=public_address,json=publicAddress" json:"public_address,omitempty"`
	// response history
	QueryOutcomes *QueryOutcomes `protobuf:"bytes,4,opt,name=query_outcomes,json=queryOutcomes" json:"query_outcomes,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Peer) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetPublicAddress() *Address {
	if m != nil {
		return m.PublicAddress
	}
	return nil
}

func (m *Peer) GetQueryOutcomes() *QueryOutcomes {
	if m != nil {
		return m.QueryOutcomes
	}
	return nil
}

// StoredRoutingTable contains the essential information associated with a routing table.
type RoutingTable struct {
	// big-endian byte representation of 32-byte self ID
	SelfId []byte `protobuf:"bytes,1,opt,name=self_id,json=selfId,proto3" json:"self_id,omitempty"`
	// array of peers in table
	Peers []*Peer `protobuf:"bytes,2,rep,name=peers" json:"peers,omitempty"`
}

func (m *RoutingTable) Reset()                    { *m = RoutingTable{} }
func (m *RoutingTable) String() string            { return proto.CompactTextString(m) }
func (*RoutingTable) ProtoMessage()               {}
func (*RoutingTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RoutingTable) GetSelfId() []byte {
	if m != nil {
		return m.SelfId
	}
	return nil
}

func (m *RoutingTable) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type DocumentMetrics struct {
	NDocuments  uint64              `protobuf:"varint,1,opt,name=n_documents,json=nDocuments" json:"n_documents,omitempty"`
	TotalSize   uint64              `protobuf:"varint,2,opt,name=total_size,json=totalSize" json:"total_size,omitempty"`
	Replication *ReplicationMetrics `protobuf:"bytes,3,opt,name=replication" json:"replication,omitempty"`
}

func (m *DocumentMetrics) Reset()                    { *m = DocumentMetrics{} }
func (m *DocumentMetrics) String() string            { return proto.CompactTextString(m) }
func (*DocumentMetrics) ProtoMessage()               {}
func (*DocumentMetrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DocumentMetrics) GetNDocuments() uint64 {
	if m != nil {
		return m.NDocuments
	}
	return 0
}

func (m *DocumentMetrics) GetTotalSize() uint64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *DocumentMetrics) GetReplication() *ReplicationMetrics {
	if m != nil {
		return m.Replication
	}
	return nil
}

type ReplicationMetrics struct {
	// n_verified is the total number of verified documents (fully or partial)
	NVerified uint64 `protobuf:"varint,1,opt,name=n_verified,json=nVerified" json:"n_verified,omitempty"`
	// n_underreplicated is the number of under-repliced documents found
	NUnderreplicated uint64 `protobuf:"varint,2,opt,name=n_underreplicated,json=nUnderreplicated" json:"n_underreplicated,omitempty"`
	// n_replicated is the number of documents successfully replicated
	NReplicated uint64 `protobuf:"varint,3,opt,name=n_replicated,json=nReplicated" json:"n_replicated,omitempty"`
	// latest_pass is the epoch time (in seconds) since the last full replication
	LatestPass int64 `protobuf:"varint,4,opt,name=latest_pass,json=latestPass" json:"latest_pass,omitempty"`
}

func (m *ReplicationMetrics) Reset()                    { *m = ReplicationMetrics{} }
func (m *ReplicationMetrics) String() string            { return proto.CompactTextString(m) }
func (*ReplicationMetrics) ProtoMessage()               {}
func (*ReplicationMetrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReplicationMetrics) GetNVerified() uint64 {
	if m != nil {
		return m.NVerified
	}
	return 0
}

func (m *ReplicationMetrics) GetNUnderreplicated() uint64 {
	if m != nil {
		return m.NUnderreplicated
	}
	return 0
}

func (m *ReplicationMetrics) GetNReplicated() uint64 {
	if m != nil {
		return m.NReplicated
	}
	return 0
}

func (m *ReplicationMetrics) GetLatestPass() int64 {
	if m != nil {
		return m.LatestPass
	}
	return 0
}

func init() {
	proto.RegisterType((*Address)(nil), "storage.Address")
	proto.RegisterType((*QueryOutcomes)(nil), "storage.QueryOutcomes")
	proto.RegisterType((*QueryTypeOutcomes)(nil), "storage.QueryTypeOutcomes")
	proto.RegisterType((*Peer)(nil), "storage.Peer")
	proto.RegisterType((*RoutingTable)(nil), "storage.RoutingTable")
	proto.RegisterType((*DocumentMetrics)(nil), "storage.DocumentMetrics")
	proto.RegisterType((*ReplicationMetrics)(nil), "storage.ReplicationMetrics")
}

func init() { proto.RegisterFile("libri/common/storage/storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x53, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x55, 0xda, 0xfc, 0xfa, 0xe7, 0xa6, 0xed, 0x6f, 0xf3, 0xc3, 0x28, 0x9b, 0xd0, 0x4a, 0x78,
	0xa9, 0x84, 0xd8, 0xa4, 0x22, 0x01, 0x2f, 0x7b, 0x40, 0x82, 0x07, 0x24, 0x10, 0x9b, 0x19, 0xbc,
	0x5a, 0x69, 0x72, 0x37, 0x59, 0x4a, 0x6c, 0xd7, 0x76, 0x90, 0xba, 0x17, 0xc4, 0x37, 0xe0, 0x33,
	0x20, 0x3e, 0x28, 0x8a, 0xed, 0xa4, 0x9d, 0x26, 0xf1, 0x54, 0x9f, 0x7b, 0x4f, 0x7d, 0xce, 0x3d,
	0xd7, 0x81, 0xb4, 0xe4, 0x6b, 0xcd, 0xcf, 0x73, 0x59, 0x55, 0x52, 0x9c, 0x1b, 0x2b, 0x75, 0x76,
	0x8b, 0xed, 0xef, 0x99, 0xd2, 0xd2, 0x4a, 0x32, 0x0c, 0x30, 0x7d, 0x01, 0xc3, 0xb7, 0x45, 0xa1,
	0xd1, 0x18, 0x32, 0x83, 0x1e, 0x57, 0xf3, 0xde, 0x22, 0x5a, 0x8e, 0x69, 0x8f, 0x2b, 0x42, 0x20,
	0x56, 0x52, 0xdb, 0x79, 0x7f, 0x11, 0x2d, 0xa7, 0xd4, 0x9d, 0xd3, 0x9f, 0x11, 0x4c, 0xaf, 0x6a,
	0xd4, 0xdb, 0xcf, 0xb5, 0xcd, 0x65, 0x85, 0x86, 0xbc, 0x82, 0x91, 0xc6, 0x4d, 0x8d, 0xc6, 0x9a,
	0x79, 0xb4, 0x88, 0x96, 0xc9, 0xea, 0xf8, 0xac, 0xd5, 0x72, 0xcc, 0xeb, 0xad, 0xc2, 0x96, 0x4d,
	0x3b, 0x2e, 0x79, 0x03, 0x63, 0x8d, 0x46, 0x49, 0x61, 0xd0, 0x38, 0xd1, 0x7f, 0xff, 0x71, 0x47,
	0x4e, 0x7f, 0xc0, 0xe1, 0x83, 0x3e, 0x39, 0x86, 0x11, 0x66, 0xba, 0xe4, 0x68, 0xac, 0xb3, 0xd1,
	0xa7, 0x1d, 0x26, 0x47, 0x30, 0x28, 0x33, 0xdb, 0x74, 0x7a, 0xae, 0x13, 0x10, 0x39, 0x81, 0xb1,
	0x60, 0x9b, 0x1a, 0x35, 0x47, 0xe3, 0xa6, 0x8c, 0xe9, 0x48, 0x5c, 0x79, 0x4c, 0x1e, 0xc3, 0x48,
	0x30, 0xd4, 0x5a, 0x6a, 0x33, 0x8f, 0x5d, 0x6f, 0x28, 0xde, 0x3b, 0x98, 0xfe, 0x8e, 0x20, 0xbe,
	0x44, 0xd4, 0x2e, 0xb1, 0xc2, 0xc9, 0x4d, 0x68, 0x8f, 0x17, 0x4d, 0x62, 0x22, 0xab, 0x30, 0x64,
	0xe8, 0xce, 0xe4, 0x35, 0xcc, 0x54, 0xbd, 0x2e, 0x79, 0xce, 0x32, 0x9f, 0xb3, 0x53, 0x4a, 0x56,
	0x07, 0xdd, 0xb0, 0x21, 0x7f, 0x3a, 0xf5, 0xbc, 0x76, 0x1d, 0x17, 0x30, 0x6b, 0xbc, 0x6d, 0x99,
	0x0c, 0x33, 0x3a, 0x1b, 0xc9, 0xea, 0xe8, 0x7e, 0x4a, 0x5d, 0x42, 0xd3, 0xcd, 0x3e, 0x4c, 0x3f,
	0xc2, 0x84, 0xca, 0xda, 0x72, 0x71, 0x7b, 0x9d, 0xad, 0x4b, 0x24, 0x8f, 0x60, 0x68, 0xb0, 0xbc,
	0x61, 0x9d, 0xe1, 0x41, 0x03, 0x3f, 0x14, 0xe4, 0x19, 0xfc, 0xa7, 0x10, 0x75, 0xb3, 0x84, 0xfe,
	0x32, 0x59, 0x4d, 0xbb, 0xeb, 0x9b, 0x11, 0xa9, 0xef, 0xa5, 0xbf, 0x22, 0xf8, 0xff, 0x9d, 0xcc,
	0xeb, 0x0a, 0x85, 0xfd, 0x84, 0x56, 0xf3, 0xdc, 0x90, 0x53, 0x48, 0x04, 0x2b, 0x42, 0xd1, 0x2f,
	0x3f, 0xa6, 0x20, 0x5a, 0x9a, 0x21, 0x4f, 0x00, 0xac, 0xb4, 0x59, 0xc9, 0x0c, 0xbf, 0xf3, 0xa1,
	0xc4, 0x74, 0xec, 0x2a, 0x5f, 0xf8, 0x1d, 0x92, 0x0b, 0x48, 0x34, 0xaa, 0x92, 0xe7, 0x99, 0xe5,
	0x52, 0x84, 0x58, 0x4e, 0x3a, 0x79, 0xba, 0xeb, 0x05, 0x45, 0xba, 0xcf, 0x4f, 0xff, 0x44, 0x40,
	0x1e, 0x72, 0x1a, 0x51, 0xc1, 0xbe, 0xa3, 0xe6, 0x37, 0x1c, 0x8b, 0x60, 0x6a, 0x2c, 0xbe, 0x85,
	0x02, 0x79, 0x0e, 0x87, 0x82, 0xd5, 0xa2, 0x40, 0xdd, 0xde, 0x85, 0x45, 0xb0, 0x76, 0x20, 0xbe,
	0xde, 0xaf, 0x93, 0xa7, 0x30, 0x11, 0x6c, 0x8f, 0xe7, 0xdf, 0x48, 0x22, 0xe8, 0x8e, 0x72, 0x0a,
	0x89, 0x7f, 0x4d, 0x4c, 0x65, 0xc6, 0xaf, 0xa8, 0x4f, 0xc1, 0x97, 0x2e, 0x33, 0x63, 0xd6, 0x03,
	0xf7, 0xc1, 0xbd, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xca, 0x70, 0x44, 0x54, 0x96, 0x03, 0x00,
	0x00,
}
