// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	Address
	Responses
	Peer
	RoutingTable
*/
package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Address is a IPv4 address.
type Address struct {
	// IP address
	Ip string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// TCP port
	Port uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// Responses contains statistics about a Peer's response history.
type Responses struct {
	// epoch time (seconds since 1970 UTC) of the earliest response from the peer
	Earliest int64 `protobuf:"varint,1,opt,name=earliest" json:"earliest,omitempty"`
	// epoch time of the latest response from the peer
	Latest int64 `protobuf:"varint,2,opt,name=latest" json:"latest,omitempty"`
	// number of queries sent to the peer
	NQueries uint64 `protobuf:"varint,3,opt,name=n_queries,json=nQueries" json:"n_queries,omitempty"`
	// number of queries that errored
	NErrors uint64 `protobuf:"varint,4,opt,name=n_errors,json=nErrors" json:"n_errors,omitempty"`
}

func (m *Responses) Reset()                    { *m = Responses{} }
func (m *Responses) String() string            { return proto.CompactTextString(m) }
func (*Responses) ProtoMessage()               {}
func (*Responses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Responses) GetEarliest() int64 {
	if m != nil {
		return m.Earliest
	}
	return 0
}

func (m *Responses) GetLatest() int64 {
	if m != nil {
		return m.Latest
	}
	return 0
}

func (m *Responses) GetNQueries() uint64 {
	if m != nil {
		return m.NQueries
	}
	return 0
}

func (m *Responses) GetNErrors() uint64 {
	if m != nil {
		return m.NErrors
	}
	return 0
}

// Peer is the basic information associated with each peer in the network.
type Peer struct {
	// big-endian byte representation of 32-byte ID
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// self-reported name of the peer
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// public IP address
	PublicAddress *Address `protobuf:"bytes,3,opt,name=public_address,json=publicAddress" json:"public_address,omitempty"`
	// response history
	Responses *Responses `protobuf:"bytes,4,opt,name=responses" json:"responses,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Peer) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetPublicAddress() *Address {
	if m != nil {
		return m.PublicAddress
	}
	return nil
}

func (m *Peer) GetResponses() *Responses {
	if m != nil {
		return m.Responses
	}
	return nil
}

// StoredRoutingTable contains the essential information associated with a routing table.
type RoutingTable struct {
	// big-endian byte representation of 32-byte self ID
	SelfId []byte `protobuf:"bytes,1,opt,name=self_id,json=selfId,proto3" json:"self_id,omitempty"`
	// array of peers in table
	Peers []*Peer `protobuf:"bytes,2,rep,name=peers" json:"peers,omitempty"`
}

func (m *RoutingTable) Reset()                    { *m = RoutingTable{} }
func (m *RoutingTable) String() string            { return proto.CompactTextString(m) }
func (*RoutingTable) ProtoMessage()               {}
func (*RoutingTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RoutingTable) GetSelfId() []byte {
	if m != nil {
		return m.SelfId
	}
	return nil
}

func (m *RoutingTable) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "storage.Address")
	proto.RegisterType((*Responses)(nil), "storage.Responses")
	proto.RegisterType((*Peer)(nil), "storage.Peer")
	proto.RegisterType((*RoutingTable)(nil), "storage.RoutingTable")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x91, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0x95, 0x34, 0x6f, 0xd3, 0x5c, 0x9b, 0xea, 0xd5, 0x0d, 0x10, 0x60, 0x89, 0xc2, 0x92,
	0x85, 0x0a, 0x95, 0x81, 0x99, 0x81, 0x01, 0x89, 0x01, 0x2c, 0xf6, 0xc8, 0x25, 0x47, 0x65, 0x29,
	0xd8, 0xe6, 0xec, 0x8a, 0x4f, 0xc2, 0xf7, 0x45, 0x71, 0xfe, 0xb0, 0xdd, 0x4f, 0xcf, 0xf9, 0xee,
	0x79, 0xce, 0x90, 0x3b, 0x6f, 0x58, 0x1e, 0x69, 0x67, 0xd9, 0x78, 0x83, 0xe9, 0x88, 0xd5, 0x0d,
	0xa4, 0x0f, 0x6d, 0xcb, 0xe4, 0x1c, 0x6e, 0x21, 0x56, 0xb6, 0x88, 0xcb, 0xa8, 0xce, 0x44, 0xac,
	0x2c, 0x22, 0x24, 0xd6, 0xb0, 0x2f, 0x16, 0x65, 0x54, 0xe7, 0x22, 0xd4, 0xd5, 0x37, 0x64, 0x82,
	0x9c, 0x35, 0xda, 0x91, 0xc3, 0x4b, 0x58, 0x91, 0xe4, 0x4e, 0x91, 0xf3, 0x45, 0x54, 0x46, 0xf5,
	0x42, 0xcc, 0x8c, 0x67, 0xb0, 0xec, 0xa4, 0xef, 0x95, 0x38, 0x28, 0x23, 0xe1, 0x15, 0x64, 0xba,
	0xf9, 0x3a, 0x11, 0x2b, 0x72, 0x61, 0x72, 0x22, 0x56, 0xfa, 0x75, 0x60, 0xbc, 0x80, 0x95, 0x6e,
	0x88, 0xd9, 0xb0, 0x2b, 0x92, 0xa0, 0xa5, 0xfa, 0x31, 0x60, 0xf5, 0x13, 0x41, 0xf2, 0x42, 0xc4,
	0xc1, 0x65, 0x1b, 0xd6, 0x6d, 0x44, 0xac, 0xda, 0xde, 0xa5, 0x96, 0x9f, 0x34, 0xfa, 0x0e, 0x35,
	0xde, 0xc3, 0xd6, 0x9e, 0x0e, 0x9d, 0x7a, 0x6f, 0xe4, 0x90, 0x2d, 0x6c, 0x5a, 0xef, 0xff, 0xef,
	0xa6, 0x2b, 0x8c, 0x99, 0x45, 0x3e, 0xf4, 0x4d, 0x27, 0xb8, 0x85, 0x8c, 0xa7, 0x78, 0xc1, 0xc1,
	0x7a, 0x8f, 0xf3, 0x9b, 0x39, 0xb8, 0xf8, 0x6b, 0xaa, 0x9e, 0x61, 0x23, 0xcc, 0xc9, 0x2b, 0x7d,
	0x7c, 0x93, 0x87, 0x8e, 0xf0, 0x1c, 0x52, 0x47, 0xdd, 0x47, 0x33, 0x7b, 0x5c, 0xf6, 0xf8, 0xd4,
	0xe2, 0x35, 0xfc, 0xb3, 0x44, 0xec, 0x8a, 0xb8, 0x5c, 0xd4, 0xeb, 0x7d, 0x3e, 0x8f, 0xed, 0x53,
	0x89, 0x41, 0x3b, 0x2c, 0xc3, 0xef, 0xdc, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xbb, 0x37,
	0xc0, 0xae, 0x01, 0x00, 0x00,
}
