scrape_configs:
- job_name: 'kubernetes-pods'
  scheme: http
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    regex: true
  - action: replace
    source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    target_label: __address__
    regex: (.+)(?::\d+);(\d+)
    replacement: $1:$2

- job_name: 'kubernetes-nodes'
  scheme: http
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  # Use insecure read-only HTTP 10255 port
  # More info is here: http://github.com/kayrus/kubelet-exploit
  - source_labels: [__address__]
    regex: '(.*):10250'
    replacement: '${1}:10255'
    target_label: __address__